-- Create the contact_requests table
create table public.contact_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text,
  subject text,
  message text not null,
  status text default 'new'
);

-- Enable Row Level Security
alter table public.contact_requests enable row level security;

-- Allow public inserts (anyone can contact)
create policy "Allow public inserts"
on public.contact_requests
for insert
to public
with check (true);

-- Allow service_role only to select (admins)
create policy "Allow service role selects"
on public.contact_requests
for select
to service_role
using (true);
